
--CONVERTING THE DATE COLUMN

ALTER TABLE NashvilleHousing
ADD [SALE DATE] DATE

UPDATE NashvilleHousing SET [SALE DATE] = CONVERT(DATE,SaleDate)


--UPDATING THE NULL VALUES IN PROPERTY ADDRESS COLUMN

UPDATE T1 SET PROPERTYADDRESS = ISNULL(T1.PropertyAddress,T2.PropertyAddress)
FROM NashvilleHousing AS T1
JOIN NashvilleHousing AS T2
ON T1.ParcelID = T2.ParcelID AND T1.[UniqueID ] <> T2.[UniqueID ]
WHERE T1.PropertyAddress IS NULL


--SPLITTING THE PROPERTY ADDRESS (ADDRESS, CITY) WITH THE HELP OF SUBSTRING FUNCTION

ALTER TABLE NASHVILLEHOUSING
ADD PROPERTY_ADDRESS NVARCHAR(255)

UPDATE NashvilleHousing
SET Property_Address = SUBSTRING(PropertyAddress,1,CHARINDEX(',',PROPERTYADDRESS)-1)

ALTER TABLE NASHVILLEHOUSING
ADD PROPERTY_ADDRESS_CITY NVARCHAR(255)

UPDATE NashvilleHousing
SET PROPERTY_ADDRESS_CITY = SUBSTRING(PropertyAddress,CHARINDEX(',',PROPERTYADDRESS)+1,LEN(PROPERTYADDRESS))

--SPLITTING THE OWNER ADDRESS WITH THE HELP OF PARSENAME FUNCTION

SELECT PARSENAME(REPLACE(OwnerAddress,',','.'),3),
PARSENAME(REPLACE(OwnerAddress,',','.'),2),
PARSENAME(REPLACE(OwnerAddress,',','.'),1)
FROM NashvilleHousing

ALTER TABLE NASHVILLEHOUSING
ADD OWNER_ADDRESS NVARCHAR(255)

UPDATE NashvilleHousing
SET OWNER_ADDRESS = PARSENAME(REPLACE(OwnerAddress,',','.'),3)

ALTER TABLE NASHVILLEHOUSING
ADD OWNER_ADDRESS_CITY NVARCHAR(255)

UPDATE NashvilleHousing
SET OWNER_ADDRESS_CITY = PARSENAME(REPLACE(OwnerAddress,',','.'),2)

ALTER TABLE NASHVILLEHOUSING
ADD OWNER_ADDRESS_STATE NVARCHAR(255)

UPDATE NashvilleHousing
SET OWNER_ADDRESS_STATE = PARSENAME(REPLACE(OwnerAddress,',','.'),1)

--CHANGE Y AND N TO YES AND NO IN "SOLD AS VACANT" COLUMN

UPDATE NashvilleHousing
SET SoldAsVacant = CASE WHEN SoldAsVacant = 'Y' THEN 'YES'
				        WHEN SoldAsVacant = 'N' THEN 'NO'
						ELSE SoldAsVacant
						END

--REMOVING DUPLICATES

WITH RowNumCTE AS(
Select *,
	ROW_NUMBER() OVER (
	PARTITION BY ParcelID,
				 PropertyAddress,
				 SalePrice,
				 SaleDate,
				 LegalReference
				 ORDER BY
					UniqueID
					) row_num
From NashvilleHousing)

DELETE
From RowNumCTE
Where row_num > 1

--DROPPING UNUSED COLUMN

ALTER TABLE NashvilleHousing
DROP COLUMN OWNERADDRESS,PROPERTYADDRESS,TAXDISTRICT,SALEDATE




